org.gradle.jvmargs=-Xmx4G -XX:MaxMetaspaceSize=1G -XX:ReservedCodeCacheSize=512m
org.gradle.configuration-cache=false
android.useAndroidX=true
org.gradle.java.installations.auto-download=true
org.gradle.java.home=C:\\Program Files\\Android\\Android Studio\\jbr
# This builtInKotlin flag was added automatically by Flutter migrator
android.builtInKotlin=true
# This newDsl flag was added automatically by Flutter migrator
android.newDsl=true
